sudo: required
services:
  - docker
script:
  - docker build -t jogendrajangid/es-curator:$TRAVIS_BUILD_NUMBER .
  - docker tag jogendrajangid/es-curator:$TRAVIS_BUILD_NUMBER jogendrajangid/es-curator:latest
  - docker login -u $user -p $passwd
  - docker push jogendrajangid/es-curator:$TRAVIS_BUILD_NUMBER
  - docker push jogendrajangid/es-curator:latest
  - docker run --rm --name es-curator --entrypoint /usr/bin/curator  jogendrajangid/es-curator:$TRAVIS_BUILD_NUMBER  --version
notifications:
  email:
    - jogendra.jangid@gmail.com
